[traefik]
  enable = true
  [traefik.http.routers.frontend]
    middlewares = "frontend-redirect"
    entryPoints = "websecure"
    rule = "Host(`yasarcakir.com`) || Host(`www.yasarcakir.com`)"
    [traefik.http.routers.frontend.tls]
      certResolver = "myresolver"
    [traefik.http.routers.frontend.loadbalancer.server]
      port = 3000
  [traefik.http.middlewares.frontend-redirect.redirectregex]
    Regex = "^(https?://)www.(.*)$$"
    Replacement = "$${1}$${2}"
  