[api]
  dashboard = true

[providers]
  [providers.docker]
    exposedByDefault = false
  [providers.file]
    filename = "/traefik_dynamic.toml"
    watch = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
    [entryPoints.web.http.redirections.entryPoint]
    to = "websecure"
    scheme = "https"

[certificatesResolvers.myresolver.acme]
  email = "dev.yasarcakir@gmail.com"
  storage = "/letsencrypt/acme.json"
  [certificatesResolvers.myresolver.acme.tlschallenge]
