[http]
  [http.routers]
    [http.routers.backend]
      rule = "Host(`api.yasarcakir.com`)"
      entryPoints = ["websecure"]
      service = "backend"
      [http.routers.backend.tls]
        certResolver = "myresolver"
  [http.services]
    [http.services.backend.loadBalancer]
      [[http.services.backend.loadBalancer.servers]]
        url = "http://127.0.0.1:4000"